enum ApiNames { 
  
  ///[Sessions]
  INIT_SESSION ,
  SESSION_CONFIGRATION,
  
  /// [Cities]
  
  GET_CITIES,

  ///[FoodCategory]
  GET_FOOD_CATEGORY,

  GET_ALL_ESTABLISHMENT_LIST,
  GET_FOOD_TYPE_LIST,
  GET_PRODUCT_LIST,
  ORDER_DELIVERY,
  ORDER_STATUS_CHECHED,
  FOOD_ORDER_LISTINGS,
  ACTIVE_COUNTS
  }